# Generated by Django 5.1.7 on 2025-04-17 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', models.TextField()),
                ('question_hint_red', models.TextField()),
                ('question_hint_green', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_completed',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_time',
        ),
        migrations.AddField(
            model_name='session',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='session',
            name='submitted_by',
            field=models.ManyToManyField(blank=True, related_name='submitted_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='session',
            name='users',
            field=models.ManyToManyField(related_name='voting_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'session', 'question')},
            },
        ),
        migrations.DeleteModel(
            name='HealthCard',
        ),
    ]
