# Generated by Django 5.1.7 on 2025-04-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_alter_session_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
