# Generated by Django 5.1.7 on 2025-04-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_session_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='questions_included',
            field=models.ManyToManyField(related_name='voting_sessions', to='voting.question'),
        ),
    ]
